config/routes.rb
Rails.application.routes.draw do
  get 'sessions/login'
  get 'login' => 'sessions#login'

  post 'sessions/login'
  post 'login' => 'sessions#login'

  get 'sessions/logout'
  get 'logout' => 'sessions#logout'

  root 'sessions#login'

  resources :grades
  resources :parents
  resources :students
  resources :teachers

end

app/models/grade.rb
class Grade < ActiveRecord::Base
  belongs_to :student

  validates :grade, presence: true
  validates :assignment_name, presence: true

end

app/controllers/grades_controller.rb
class GradesController < ApplicationController
  before_action :set_grade, only: [:show, :edit, :update, :destroy]

  def index
    @grades = Grade.all
  end

  def show
  end

  def new
    @grade = Grade.new
  end

  def edit
  end

  def create
    @grade = Grade.new(grade_params)
    if @grade.save
      redirect_to @grade, notice: 'Grade was successfully created.'
    else
      render :new
    end
  end

  def update
    if @grade.update(grade_params)
      redirect_to teachers_path, notice: 'Grade was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @grade.destroy
      redirect_to grades_url, notice: 'Grade was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_grade
      @grade = Grade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def grade_params
      params.require(:grade).permit(:grade, :assignment_name, :student_id)
    end
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/views/grades/_form.html.erb
<%= form_for(@grade) do |f| %>
  <% if @grade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@grade.errors.count, "error") %> prohibited this grade from being saved:</h2>

      <ul>
      <% @grade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :grade %><br>
    <%= f.number_field :grade, :step => 'any'%>
  </div>
  <div class="field">
    <%= f.label :assignment_name %><br>
    <%= f.text_field :assignment_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/grades/edit.html.erb
<h1>Editing Grade</h1>

<%= render 'form' %>

<%= link_to 'Student List', teachers_path %>

app/views/grades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Grades</h1>

<table>
  <thead>
    <tr>
      <th>Grade</th>
      <th>Assignment name</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @grades.each do |grade| %>
      <tr>
        <td><%= grade.grade %></td>
        <td><%= grade.assignment_name %></td>
        <td><%= grade.student_id %></td>
        <td><%= link_to 'Show', grade %></td>
        <td><%= link_to 'Edit', edit_grade_path(grade) %></td>
        <td><%= link_to 'Destroy', grade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Grade', new_grade_path %>

app/views/grades/new.html.erb
<h1>New Grade</h1>

<%= render 'form' %>

<%= link_to 'Back', grades_path %>

app/views/grades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Grade:</strong>
  <%= @grade.grade %>
</p>

<p>
  <strong>Assignment name:</strong>
  <%= @grade.assignment_name %>
</p>

<p>
  <strong>Student:</strong>
  <%= @grade.student_id %>
</p>

<%= link_to 'Edit', edit_grade_path(@grade) %> |
<%= link_to 'Back', grades_path %>