config/routes.rb
Rails.application.routes.draw do
  get 'sessions/login'
  get 'login' => 'sessions#login'

  post 'sessions/login'
  post 'login' => 'sessions#login'

  get 'sessions/logout'
  get 'logout' => 'sessions#logout'

  root 'sessions#login'

  resources :grades
  resources :parents
  resources :students
  resources :teachers

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_secure_password

  has_many :students
  accepts_nested_attributes_for :students

  validates :name, presence: true
  validates :email, presence: true

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :logged_in?
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  def index
    @teacher = Teacher.find_by_id(session[:teacher_id])
    @students = Student.where(teacher_id: session[:teacher_id])
  end

  def show
  end

  def new
    @teacher = Teacher.new
  end

  def edit
    @teacher = Teacher.find_by_id(session[:teacher_id])
  end

  def create
    @teacher = Teacher.new(teacher_params)
    if @teacher.save
      redirect_to @teacher, notice: 'Teacher was successfully created.'
    else
      render :new
    end
  end

  def update
    if @teacher.update(teacher_params)
      redirect_to teachers_path, notice: 'Teacher was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @teacher.destroy
    redirect_to teachers_url, notice: 'Teacher was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(session[:teacher_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :email, :password, :teacher_id, :password_confirmation)
    end

    def logged_in?
      if session[:user_type] == "parent" || session[:user_type] == "student"
        redirect_to login_path, notice: "You can't view that page"
      else
        true
      end
    end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_field :password %>
  </div>

  <h3>Students</h3>
  <%= f.fields_for(:students) do |ff| %>
    <div class="field">
      <%= ff.label :name %><br>
      <%= ff.text_field :name %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<h2> You are logged in as <%= @teacher.name %> </h2>
<p id="notice"><%= notice %></p>

<h1>Student List</h1>

<table>
  <thead>
    <tr>
      <th>Student Name</th>
      <th>Email</th>
      <th>Parent Name</th>
      <th>Assignment Comments</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <% if student.grades.count == 0 %>
        <tr>
          <td><%= student.name %></td>
          <td><%= student.email %></td>
          <% if student.parents.count == 0 %>
            <td>N/A</td>
          <% elsif student.parents.count == 1 %>
            <td><%= student.parents.first.name %></td>
          <% else %>
            <td><%= student.parents.first.name %> and <%= student.parents.last.name %></td>
          <% end %>
          <td>No grades yet.</td>
          <td><%= link_to 'Edit', edit_grade_path(student) %></td>
      <% else %>
        <% student.grades.each do |g| %>
          <tr>
            <td><%= student.name %></td>
            <td><%= student.email %></td>
            <% if student.parents.count == 0 %>
              <td>N/A</td>
            <% elsif student.parents.count == 1 %>
              <td><%= student.parents.first.name %></td>
            <% else %>
              <td><%= student.parents.first.name %> and <%= student.parents.last.name %></td>
            <% end %>
            <td><%= g.grade %> on <%= g.assignment_name%></td>
            <td><%= link_to 'Edit', edit_grade_path(student) %></td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @teacher.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @teacher.password_digest %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>