config/routes.rb
Rails.application.routes.draw do
  get 'sessions/login'
  get 'login' => 'sessions#login'

  post 'sessions/login'
  post 'login' => 'sessions#login'

  get 'sessions/logout'
  get 'logout' => 'sessions#logout'

  root 'sessions#login'

  resources :grades
  resources :parents
  resources :students
  resources :teachers

end

app/models/parent.rb
class Parent < ActiveRecord::Base
  has_secure_password
  belongs_to :student

  validates :name, presence: true
  validates :email, presence: true

end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action :logged_in?, except: [:new, :create]
  before_action :set_parent, only: [:show, :edit, :update, :destroy]

  def new
    if session[:teacher_id]
      @parent = Parent.new
    else
      flash.now[:alert] = "You can't access this page"
    end
  end

  def create
    @parent = Parent.new(parent_params)
    @parent.teacher_id = session[:teacher_id]
    if @parent.save
      redirect_to teachers_path, notice: 'Parent was successfully created.'
    else
      render :new
    end
  end

  def index
    @parent = Parent.find_by_id(session[:parent_id])
    @kid = @parent.student 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parent
      @parent = Parent.find(session[:parent_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parent_params
      params.require(:parent).permit(:name, :email, :password, :teacher_id, :password_confirmation)
    end

    def logged_in?
      if session[:user_type] == "student" || session[:user_type] == "teacher"
        redirect_to login_path, notice: "You can't view that page"
      else
        true
      end
    end
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/views/parents/_form.html.erb
<%= form_for(@parent) do |f| %>
  <% if @parent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parent.errors.count, "error") %> prohibited this parent from being saved:</h2>

      <ul>
      <% @parent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.text_field :password_digest %>
  </div>
  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.number_field :student_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parents/index.html.erb
<h2> You are logged in as <%= @parent.name %> </h2>
<p id="notice"><%= notice %></p>

<h3>Grade List for <%= @kid.name %></h3>

<table>
  <thead>
    <tr>
      <th>Assignment</th>
      <th>Grade</th>
    </tr>
  </thead>

  <tbody>
    <% @kid.grades.each do |g| %>
      <tr>
        <td><%= g.assignment_name %></td>
        <td><%= g.grade %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/parents/new.html.erb
<h1>New Parent</h1>

<%= render 'form' %>

<%= link_to 'Back', parents_path %>